# Generated by Django 5.2.3 on 2025-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
