# Generated by Django 5.2.3 on 2025-09-20 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_datastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
